# Generated by Django 4.2.6 on 2023-10-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_employeereview_empreviewquesans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeereview',
            name='CoeMail',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='CoeMailIds',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='DirectMail',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='DirectMailIds',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='GroupHr',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='GroupHrIds',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='HodMail',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='HodMailIds',
        ),
    ]
