# Generated by Django 4.2.6 on 2023-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_employeereview_coemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreviewquesans',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
