# Generated by Django 4.2.6 on 2023-10-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_empreviewquesans_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreviewquesans',
            name='Question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_question_employee_review', to='review.categoryquestion'),
        ),
    ]
