# Generated by Django 4.2.6 on 2023-10-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_employeemaster_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0006_alter_empreviewquesans_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeereview',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='SubmittedBy',
        ),
        migrations.AddField(
            model_name='empreviewquesans',
            name='data_is_upload_backend',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmpReviewRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('final_status', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_review', to='common.employeemaster')),
                ('SubmittedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_employee_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
