# Generated by Django 4.2.6 on 2023-10-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_remove_employeereview_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereview',
            name='employee_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_root_category_review', to='review.empreviewroot'),
        ),
    ]
