# Generated by Django 4.2.6 on 2023-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_employeereview_employee_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryquestion',
            name='QUESTION_TYPE',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
    ]
