# Generated by Django 4.2.6 on 2023-10-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_categoryquestion_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryquestion',
            name='QUESTION_TYPE',
        ),
    ]
