# Generated by Django 4.2.6 on 2026-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_remove_categoryquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryquestion',
            name='Options',
            field=models.CharField(blank=True, help_text='Comma-separated. Only used when WidgetType = Dropdown. e.g. Excellent,Good,Average,Poor', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoryquestion',
            name='WidgetType',
            field=models.CharField(choices=[('tri_yes', 'Tri-State (Yes / N/A / No)'), ('tri_rag', 'Tri-State (Red / Amber / Green)'), ('dropdown', 'Dropdown'), ('textbox', 'Text Box'), ('textarea', 'Text Area'), ('date', 'Date Picker')], default='tri_yes', max_length=20),
        ),
    ]
