# Generated by Django 4.2.6 on 2026-07-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_categoryquestion_options_categoryquestion_widgettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryquestion',
            name='RemarkEnabled',
            field=models.BooleanField(default=True, help_text='Uncheck to disable/grey-out the Remarks box for this question.'),
        ),
    ]
