# Generated by Django 4.2.6 on 2023-10-05 10:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('DeptName', models.CharField(max_length=100)),
                ('CoeLeadEmpid', models.CharField(max_length=100, null=True)),
                ('GPOLeadEmpid', models.CharField(max_length=100, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('EmployeeNumber', models.CharField(max_length=500, null=True, unique=True)),
                ('EmployeeName', models.CharField(max_length=500, null=True)),
                ('DateOfBirth', models.CharField(max_length=500, null=True)),
                ('EnterpriseHireDate', models.CharField(max_length=500, null=True)),
                ('LegalEntity', models.CharField(max_length=255, null=True)),
                ('AssignmentStatusType', models.CharField(max_length=255, null=True)),
                ('PersonType', models.CharField(max_length=255, null=True)),
                ('AssignmentType', models.CharField(max_length=255, null=True)),
                ('EmployeePhoneNumber', models.CharField(max_length=255, null=True)),
                ('EmailAddress', models.CharField(max_length=255, null=True)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('DepartmentReportingName', models.CharField(max_length=255, null=True)),
                ('Position', models.CharField(max_length=255, null=True)),
                ('PositionCode', models.CharField(max_length=255, null=True)),
                ('GradeName', models.CharField(max_length=255, null=True)),
                ('GradeCode', models.CharField(max_length=255, null=True)),
                ('Location', models.CharField(max_length=255, null=True)),
                ('BusinessUnit', models.CharField(max_length=255, null=True)),
                ('BusinessArea', models.CharField(max_length=255, null=True)),
                ('CostCenter', models.CharField(max_length=255, null=True)),
                ('CompanyCode', models.CharField(max_length=255, null=True)),
                ('LineManagerName', models.CharField(max_length=255, null=True)),
                ('LineManagerPersonNumber', models.CharField(max_length=255, null=True)),
                ('LineManagerPositionCode', models.CharField(max_length=255, null=True)),
                ('payroll', models.CharField(max_length=255, null=True)),
                ('COE', models.CharField(max_length=255, null=True)),
                ('Role', models.CharField(max_length=255, null=True)),
                ('Vertical', models.CharField(max_length=255, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_employees', to='common.deptmaster')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
