# Generated by Django 4.2.6 on 2023-10-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemaster',
            old_name='EnterpriseHireDate',
            new_name='AdaniExperience',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='AssignmentStatusType',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='AssignmentType',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='BusinessArea',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='COE',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='CompanyCode',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='CostCenter',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='EmailAddress',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='EmployeePhoneNumber',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='GradeName',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='LineManagerName',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='LineManagerPersonNumber',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='LineManagerPositionCode',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='PersonType',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='Vertical',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='payroll',
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='Age',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='DateOfJoin',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='DateOfRetirement',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='DateOfSeparation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='DepartmentOfOracleString',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='DomicileState',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='EmployeeStatus',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='EmployeeType',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='FunctionalManagerFullName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='FunctionalManagerID',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='GroupOfDateOfJoin',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='HODEMPID',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='HODFullName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='KRAStatus',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='MaritalStatus',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='PreviousExperience',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='ReportingMangerFullName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='ReportingMangerID',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='ReportingMangerPosition',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='TotalYearOfExperience',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
