# Generated by Django 4.2.6 on 2023-10-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_enterprisehiredate_employeemaster_adaniexperience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemaster',
            options={},
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='created',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='status',
        ),
    ]
