# Generated by Django 4.2.6 on 2026-07-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_employeemaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='Compliance_Training_Status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='Education',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='Hod',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='Last_Promotion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='Last_Transfer_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='Total_Experience',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='UJR',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
