# Generated by Django 4.2.6 on 2026-07-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_employeemaster_compliance_training_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
