# Generated by Django 4.2.6 on 2026-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_employeemaster_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='Total_Experience',
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='DateOfJoin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='DateOfRetirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='DateOfSeparation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='GroupOfDateOfJoin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
